server:
  port: 9001

spring:
  h2:
    console:
      enabled: true  # Enables H2 database web console: http://localhost:{server.port}/h2-console
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/authzdb  # File-based database
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate auto-DDL since we'll use our own ddl scripts
    database-platform: org.hibernate.dialect.H2Dialect
    # Show SQL queries in the console (optional)
    show-sql: true
  sql:
    init:
      platform: h2
      mode: always
